docker pull apache/kafka:3.7.1
docker pull neo4j:5-community
docker pull postgres:17-alpine
docker pull valkey/valkey:8-alpine
docker pull chromadb/chroma:1.5.9
docker pull moe-embed:local
docker pull prom/prometheus:latest
docker pull tecnativa/docker-socket-proxy:0.3.0
docker pull grafana/grafana:latest
docker pull prom/node-exporter:latest
docker pull gcr.io/cadvisor/cadvisor:latest
docker pull squidfunk/mkdocs-material:latest
docker pull python:3.12-alpine
docker pull amir20/dozzle:latest
docker pull scrapinghub/splash:latest
docker pull dxflrs/garage:v1.0.1
docker pull caddy:2-alpine
docker pull postgres:16-alpine
docker pull valkey/valkey:8-alpine
docker pull ghcr.io/goauthentik/server:${AUTHENTIK_TAG}
docker pull ghcr.io/goauthentik/server:${AUTHENTIK_TAG}
