#!/usr/bin/env python3
"""Validate MoE Sovereign governance files and generated catalogs."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from urllib.parse import unquote


ROOT = Path(__file__).resolve().parents[1]
ENTRYPOINT_SOURCE = ROOT / "configs/runtime_entrypoints.json"
ENTRYPOINT_CATALOG = ROOT / "docs/generated/runtime-entrypoints.md"

REQUIRED_FILES = (
    "AGENTS.md",
    "CLAUDE.md",
    "PROJECT_COMPLIANCE.md",
    ".claude/rules/security.md",
    ".claude/rules/python.md",
    ".claude/rules/tests.md",
    ".claude/rules/deployment.md",
    "docs/ai-memory/INDEX.md",
    "docs/ai-memory/00-restore-protocol.md",
    "docs/ai-memory/01-authority-and-architecture.md",
    "docs/ai-memory/06-testing-deploy-and-coverage.md",
    "docs/ai-memory/07-current-status-and-next-work.md",
    "docs/backlog/backlog.md",
    "docs/backlog/current/current.md",
    "docs/backlog/current/dependency-map.md",
    "docs/backlog/current/roadmap.md",
    "docs/backlog/current/stories.md",
    "docs/backlog/current/implementation-tasks.md",
    "docs/backlog/current/I-1-sovereign-sft/initiative.md",
    "docs/backlog/current/I-2-pipeline-quality-gate/initiative.md",
    "docs/backlog/current/I-2-pipeline-quality-gate/E-2.1-deterministic-signals/epic.md",
    "docs/backlog/current/I-2-pipeline-quality-gate/E-2.2-trust-score-self-critique/epic.md",
    "docs/backlog/current/I-2-pipeline-quality-gate/E-2.3-context-resilience/epic.md",
    "docs/backlog/current/I-2-pipeline-quality-gate/E-2.4-complexity-classification/epic.md",
    "docs/backlog/current/I-2-pipeline-quality-gate/E-2.5-multi-tenant/epic.md",
    "configs/runtime_entrypoints.json",
    "docs/generated/runtime-entrypoints.md",
)

METADATA_FILES = (
    "AGENTS.md",
    "PROJECT_COMPLIANCE.md",
    "docs/ai-memory/INDEX.md",
    "docs/ai-memory/00-restore-protocol.md",
    "docs/ai-memory/01-authority-and-architecture.md",
    "docs/ai-memory/06-testing-deploy-and-coverage.md",
    "docs/ai-memory/07-current-status-and-next-work.md",
    "docs/backlog/backlog.md",
    "docs/backlog/current/current.md",
    "docs/backlog/current/dependency-map.md",
    "docs/backlog/current/roadmap.md",
)

LINK_FILES = tuple(path for path in REQUIRED_FILES if path.endswith(".md"))
LOCAL_LINK_RE = re.compile(r"(?<!!)\[[^\]]+\]\(([^)]+)\)")
DIRECT_MAIN_PUSH_RE = re.compile(
    r"^\s*(?:[-*]\s*)?`?git\s+push\s+\S+\s+(?:refs/heads/)?main(?:\s|`|$)",
    re.IGNORECASE | re.MULTILINE,
)
SECRET_PATTERNS = (
    re.compile(r"moe-sk-[A-Za-z0-9_-]{24,}"),
    re.compile(r"(?<![A-Za-z0-9])sk-[A-Za-z0-9_-]{32,}"),
)
BLANKET_FAIL_OPEN = (
    "all checks fail-open",
    "alle checks fail-open",
    "all three mechanisms fail-open",
)


def _escape_cell(value: object) -> str:
    return str(value).replace("|", r"\|").replace("\n", " ")


def load_entrypoints() -> dict:
    data = json.loads(ENTRYPOINT_SOURCE.read_text(encoding="utf-8"))
    if data.get("schema_version") != 1:
        raise ValueError("configs/runtime_entrypoints.json must use schema_version 1")
    entries = data.get("entrypoints")
    if not isinstance(entries, list):
        raise ValueError("runtime entrypoints must be a list")
    return data


def validate_entrypoints(data: dict) -> list[str]:
    errors: list[str] = []
    seen: set[tuple[str, str]] = set()
    required = {"path", "qualname", "kind", "wiring_path", "wiring_marker"}
    for index, item in enumerate(data["entrypoints"]):
        missing = sorted(required - set(item))
        if missing:
            errors.append(f"runtime entrypoint #{index} missing: {', '.join(missing)}")
            continue
        key = (str(item["path"]), str(item["qualname"]))
        if key in seen:
            errors.append(f"duplicate runtime entrypoint: {key[0]}::{key[1]}")
        seen.add(key)
        declared = ROOT / str(item["path"])
        wiring = ROOT / str(item["wiring_path"])
        if not declared.is_file():
            errors.append(f"runtime entrypoint declaration missing: {item['path']}")
        if not wiring.is_file():
            errors.append(f"runtime entrypoint wiring file missing: {item['wiring_path']}")
            continue
        marker = str(item["wiring_marker"])
        if marker not in wiring.read_text(encoding="utf-8"):
            errors.append(
                f"runtime entrypoint wiring marker missing: "
                f"{item['wiring_path']}::{marker}"
            )
    return errors


def render_entrypoint_catalog(data: dict) -> str:
    entries = sorted(
        data["entrypoints"],
        key=lambda item: (item["kind"], item["path"], item["qualname"]),
    )
    lines = [
        "# Runtime Entry-Point Catalog",
        "",
        "<!-- Generated by scripts/check_governance.py; do not edit manually. -->",
        "",
        "Source: `configs/runtime_entrypoints.json`  ",
        f"Schema version: {data['schema_version']}  ",
        f"Declared dynamic/framework entry points: {len(entries)}",
        "",
        "These callbacks are reached by a framework or protocol and therefore may",
        "not have a normal Python call site. The wiring marker is executable",
        "evidence checked by CI; it is not an end-to-end production claim.",
        "",
        "| Kind | Entry point | Declared in | Wiring evidence |",
        "|---|---|---|---|",
    ]
    for item in entries:
        lines.append(
            "| `{kind}` | `{qualname}` | `{path}` | `{wiring_path}` → "
            "`{wiring_marker}` |".format(
                **{key: _escape_cell(value) for key, value in item.items()}
            )
        )
    lines.extend(
        [
            "",
            "Add or remove entries only through the JSON inventory and accompany the",
            "change with the relevant reachability/contract test.",
            "",
        ]
    )
    return "\n".join(lines)


def check_required_files() -> list[str]:
    return [
        f"required file missing: {path}"
        for path in REQUIRED_FILES
        if not (ROOT / path).is_file()
    ]


def check_metadata() -> list[str]:
    errors: list[str] = []
    markers = ("Owner:", "Version:", "Last verified:")
    for relative in METADATA_FILES:
        path = ROOT / relative
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8")
        for marker in markers:
            if marker not in text:
                errors.append(f"{relative} missing metadata marker: {marker}")
    return errors


def check_local_links() -> list[str]:
    errors: list[str] = []
    for relative in LINK_FILES:
        path = ROOT / relative
        if not path.is_file():
            continue
        for raw_target in LOCAL_LINK_RE.findall(path.read_text(encoding="utf-8")):
            target = raw_target.strip().split(maxsplit=1)[0].strip("<>")
            if (
                not target
                or target.startswith(("#", "http://", "https://", "mailto:"))
            ):
                continue
            target = unquote(target.split("#", 1)[0])
            if not target:
                continue
            resolved = (path.parent / target).resolve()
            try:
                resolved.relative_to(ROOT)
            except ValueError:
                errors.append(f"{relative} link escapes repository: {raw_target}")
                continue
            if not resolved.exists():
                errors.append(f"{relative} broken local link: {raw_target}")
    return errors


def tracked_files() -> list[Path]:
    result = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=ROOT,
        check=True,
        capture_output=True,
    )
    return [
        ROOT / item.decode("utf-8")
        for item in result.stdout.split(b"\0")
        if item
    ]


def check_secrets() -> list[str]:
    errors: list[str] = []
    candidates = set(tracked_files())
    candidates.update(ROOT / relative for relative in REQUIRED_FILES)
    for path in sorted(candidates):
        if not path.is_file():
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        for pattern in SECRET_PATTERNS:
            if pattern.search(text):
                errors.append(
                    f"possible committed API secret: {path.relative_to(ROOT)}"
                )
                break
    return errors


def check_policy_markers() -> list[str]:
    errors: list[str] = []
    agents = (ROOT / "AGENTS.md").read_text(encoding="utf-8")
    compliance = (ROOT / "PROJECT_COMPLIANCE.md").read_text(encoding="utf-8")
    claude = (ROOT / "CLAUDE.md").read_text(encoding="utf-8")
    required_agents = (
        "sessionmesh_get_handoff",
        "Never push directly to `main`",
        "one monotonic deadline",
        "Do not persist hidden chain-of-thought",
        "isolated Git worktrees",
    )
    required_compliance = (
        "Failure-semantics matrix",
        "Authentication and API-key validity",
        "`local_only` and endpoint-locality resolution",
        "Known implementation variances",
    )
    for marker in required_agents:
        if marker not in agents:
            errors.append(f"AGENTS.md missing policy marker: {marker}")
    for marker in required_compliance:
        if marker not in compliance:
            errors.append(f"PROJECT_COMPLIANCE.md missing policy marker: {marker}")
    if "@AGENTS.md" not in claude:
        errors.append("CLAUDE.md must import @AGENTS.md")

    governed_text = "\n".join(
        (ROOT / relative).read_text(encoding="utf-8")
        for relative in LINK_FILES
        if (ROOT / relative).is_file()
    ).lower()
    for phrase in BLANKET_FAIL_OPEN:
        if phrase in governed_text:
            errors.append(f"blanket failure-semantics phrase is forbidden: {phrase}")

    for relative in ("AGENTS.md", "CLAUDE.md", "PROJECT_COMPLIANCE.md"):
        text = (ROOT / relative).read_text(encoding="utf-8")
        if DIRECT_MAIN_PUSH_RE.search(text):
            errors.append(f"{relative} documents a direct push to main command")
    return errors


def check_generated_catalog(expected: str) -> list[str]:
    if not ENTRYPOINT_CATALOG.is_file():
        return ["generated runtime entrypoint catalog is missing"]
    actual = ENTRYPOINT_CATALOG.read_text(encoding="utf-8")
    if actual != expected:
        return [
            "docs/generated/runtime-entrypoints.md is stale; "
            "run scripts/check_governance.py --write"
        ]
    return []


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()

    try:
        data = load_entrypoints()
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"governance error: {exc}", file=sys.stderr)
        return 1

    expected_catalog = render_entrypoint_catalog(data)
    if args.write:
        ENTRYPOINT_CATALOG.parent.mkdir(parents=True, exist_ok=True)
        ENTRYPOINT_CATALOG.write_text(expected_catalog, encoding="utf-8")
        print(f"wrote {ENTRYPOINT_CATALOG.relative_to(ROOT)}")
        return 0

    errors: list[str] = []
    errors.extend(check_required_files())
    errors.extend(check_metadata())
    errors.extend(validate_entrypoints(data))
    errors.extend(check_generated_catalog(expected_catalog))
    errors.extend(check_local_links())
    errors.extend(check_policy_markers())
    errors.extend(check_secrets())

    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1
    print(
        "Governance check passed: "
        f"{len(REQUIRED_FILES)} required files, "
        f"{len(data['entrypoints'])} runtime entry points."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
